'''
    File name: api_wrapper.py
    Author: Ravi Teja Nagamothu
    Date created: 7/11/2017
    Python Version: 3.6
'''

import libRSE
import bsm
import cam
import coc_script
import tc_specific
import libKPI
import bblogs
bsm._logger_bsm = libRSE._logger_libRSE


def api_wrapper_func(command):
    api_data_struct = {
        "show app store-repeat status": libRSE.show_app_store_repeat,
        "show app store-repeat streaming mode": libRSE.show_app_store_repeat,
        "show app store-repeat streaming port": libRSE.show_app_store_repeat,
        "show app store-repeat streaming ipaddr": libRSE.show_app_store_repeat,
        "show app store-repeat security certificate-attachrate":
        libRSE.show_app_store_repeat,
        "show app store-repeat security ssp-list": libRSE.show_app_store_repeat,
        "show app store-repeat all": libRSE.show_app_store_repeat,
        "show app immediate-forward status": libRSE.show_app_immediate_fwd,
        "show app immediate-forward listenerport": libRSE.show_app_immediate_fwd,
        "show app immediate-forward streaming mode": libRSE.show_app_immediate_fwd,
        "show app immediate-forward streaming port": libRSE.show_app_immediate_fwd,
        "show app immediate-forward streaming ip": libRSE.show_app_immediate_fwd,
        "show app immediate-forward tcdlisten":
        libRSE.show_app_immediate_fwd_tcdlisten,
        "show app immediate-forward security certificate-attachrate":
        libRSE.show_app_immediate_fwd,
        "show app immediate-forward all": libRSE.show_app_immediate_fwd,
        "show app gpsoutput status": libRSE.show_app_gpsoutput,
        "show app gpsoutput ipaddr": libRSE.show_app_gpsoutput,
        "show app gpsoutput port": libRSE.show_app_gpsoutput,
        "show app gpsoutput interval": libRSE.show_app_gpsoutput,
        "show app gpsoutput maximum-deviation": libRSE.show_app_gpsoutput,
        "show app gpsoutput reference-elevation": libRSE.show_app_gpsoutput,
        "show app gpsoutput time-src-lost-intrvl": libRSE.show_app_gpsoutput,
        "show app gpsoutput reference-longitude": libRSE.show_app_gpsoutput,
        "show app gpsoutput reference-latitude": libRSE.show_app_gpsoutput,
        "show app gpsoutput output-interface": libRSE.show_app_gpsoutput,
        "show app gpsoutput gpsoutput-string": libRSE.show_app_gpsoutput,
        "show app gpsoutput all": libRSE.show_app_gpsoutput,
        "show app radio radio1 name": libRSE.show_app_radio,
        "show app radio radio1 chan-mode": libRSE.show_app_radio,
        "show app radio radio1 cch": libRSE.show_app_radio,
        "show app radio radio1 svc": libRSE.show_app_radio,
        "show app radio radio2 name": libRSE.show_app_radio,
        "show app radio radio2 chan-mode": libRSE.show_app_radio,
        "show app radio radio2 cch": libRSE.show_app_radio,
        "show app radio radio2 svc": libRSE.show_app_radio,
        "show app radio all": libRSE.show_app_radio,
        "show app ipv6-provider status": libRSE.show_app_ipv6_provider,
        "show app ipv6-provider wsa repeat-rate": libRSE.show_app_ipv6_provider,
        "show app ipv6-provider wsa advertiser_id": libRSE.show_app_ipv6_provider,
        "show app ipv6-provider wsa security status":
        libRSE.show_app_ipv6_provider,
        "show app ipv6-provider wra prefix": libRSE.show_app_ipv6_provider,
        "show app ipv6-provider wra lifetime": libRSE.show_app_ipv6_provider,
        "show app ipv6-provider wra prefixlen": libRSE.show_app_ipv6_provider,
        "show app ipv6-provider wra gateway-address ipv6":
        libRSE.show_app_ipv6_provider,
        "show app ipv6-provider wra gateway-address mac":
        libRSE.show_app_ipv6_provider,
        "show app ipv6-provider wra dns primary": libRSE.show_app_ipv6_provider,
        "show app ipv6-provider all": libRSE.show_app_ipv6_provider,
        "show app dsrc-message-forward status": libRSE.show_app_dsrc_msgfwd,
        "show app dsrc-message-forward psid": libRSE.show_app_dsrc_msgfwd,
        "show app dsrc-message-forward all": libRSE.show_app_dsrc_msgfwd,
        "show app tcd status": libRSE.show_app_tcd,
        "show app tcd mode": libRSE.show_app_tcd,
        "show app tcd ntcip tc-ipaddr": libRSE.show_app_tcd,
        "show app tcd ntcip tc-port": libRSE.show_app_tcd,
        "show app tcd ntcip tc-type": libRSE.show_app_tcd,
        "show app tcd ntcip spat-tx-intvl": libRSE.show_app_tcd,
        "show app tcd ntcip map-tx-intvl": libRSE.show_app_tcd,
        "show app tcd ntcip send-red-states status": libRSE.show_app_tcd,
        "show app tcd broadcast port": libRSE.show_app_tcd,
        "show app tcd spat psid": libRSE.show_app_tcd,
        "show app tcd spat priority": libRSE.show_app_tcd,
        "show app tcd spat signature": libRSE.show_app_tcd,
        "show app tcd spat encryption": libRSE.show_app_tcd,
        "show app tcd spat transmit-enabled-lanes status": libRSE.show_app_tcd,
        "show app tcd spat certificate-attachrate": libRSE.show_app_tcd,
        "show app tcd spat certificate-optimization": libRSE.show_app_tcd,
        "show app tcd map psid": libRSE.show_app_tcd,
        "show app tcd map priority": libRSE.show_app_tcd,
        "show app tcd map signature": libRSE.show_app_tcd,
        "show app tcd map encryption": libRSE.show_app_tcd,
        "show app tcd map mapfile": libRSE.show_app_tcd,
        "show app tcd map certificate-attachrate": libRSE.show_app_tcd,
        "show app tcd all": libRSE.show_app_tcd,
        "show app ntpclient hostname": libRSE.show_app_ntpclient,
        "show app rtcm status": libRSE.show_app_rtcm,
        "show app rtcm localPort": libRSE.show_app_rtcm,
        "show app rtcm psid": libRSE.show_app_rtcm,
        "show app rtcm ifmPort": libRSE.show_app_rtcm,
        "show app rtcm preambleCrc": libRSE.show_app_rtcm,
        "show app rtcm security": libRSE.show_app_rtcm,
        "show app rtcm all": libRSE.show_app_rtcm,
        "show app store-repeat filepath": libRSE.show_app_store_repeat_fp,
        "show system hwclock": libRSE.show_system_hwclock,
        "show system settings hostname": libRSE.show_system_settings,
        "show system settings timezone": libRSE.show_system_settings,
        "show system settings all": libRSE.show_system_settings,
        "show system date": libRSE.show_system_date,
        "show system disk-usage": libRSE.show_system_disk_usage,
        "show system memory-usage": libRSE.show_system_memory_usage,
        "show system cpu-usage": libRSE.show_system_cpu_usage,
        "show system system-log status": libRSE.show_system_sys_log,
        "show system system-log loglevel": libRSE.show_system_sys_log,
        "show system system-log closeday": libRSE.show_system_sys_log,
        "show system system-log deleteday": libRSE.show_system_sys_log,
        "show system system-log deleteage": libRSE.show_system_sys_log,
        "show system system-log closetime": libRSE.show_system_sys_log,
        "show system system-log all": libRSE.show_system_sys_log,
        "show system uptime": libRSE.show_system_uptime,
        "show system interface-log status": libRSE.show_system_interface_log,
        "show system interface-log ethernet": libRSE.show_system_interface_log,
        "show system interface-log radio1": libRSE.show_system_interface_log,
        "show system interface-log radio2": libRSE.show_system_interface_log,
        "show system interface-log all": libRSE.show_system_interface_log,
        "show system network eth0 proto": libRSE.show_system_network,
        "show system network eth0 ip address": libRSE.show_system_network,
        "show system network eth0 ip netmask": libRSE.show_system_network,
        "show system network eth0 ip gateway": libRSE.show_system_network,
        "show system network eth0 macaddr": libRSE.show_system_network,
        "show system network eth0 ip6 address": libRSE.show_system_network,
        "show system network eth0 ip6 netmask": libRSE.show_system_network,
        "show system network eth0 ip6 gateway": libRSE.show_system_network,
        "show system network eth0 all": libRSE.show_system_network,
        "show system network radio1 proto": libRSE.show_system_network,
        "show system network radio1 macaddr": libRSE.show_system_network,
        "show system network radio1 ip6 address": libRSE.show_system_network,
        "show system network radio1 ip6 gateway": libRSE.show_system_network,
        "show system network radio1 all": libRSE.show_system_network,
        "show system network radio2 proto": libRSE.show_system_network,
        "show system network radio2 macaddr": libRSE.show_system_network,
        "show system network radio2 ip6 address": libRSE.show_system_network,
        "show system network radio2 ip6 gateway": libRSE.show_system_network,
        "show system network radio2 all": libRSE.show_system_network,
        "show system network all": libRSE.show_system_network,
        "show system firewall": libRSE.show_system_firewall,
        "show system acl list ipv4": libRSE.show_system_acl,
        "show system acl list ipv6": libRSE.show_system_acl,
        "show system acl list all": libRSE.show_system_acl,
        "show system gpsstatus": libRSE.show_system_gpsstatus,
        "show system process-list": libRSE.show_system_process_list,
        "show system rsu-stats store-repeat": libRSE.show_system_rsu_stats,
        "show system rsu-stats immediate-forward": libRSE.show_system_rsu_stats,
        "show system rsu-stats ipv6-provider": libRSE.show_system_rsu_stats,
        "show system rsu-stats rtcm_msg_fwd": libRSE.show_system_rsu_stats,
        "show system rsu-stats all": libRSE.show_system_rsu_stats,
        "show system rsu-uptime gpsd": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime smgrd": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime security-services": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime savari16093d-radio1": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime savari16093d-radio2": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime dsrc-message-forward": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime store-repeat": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime immediate-forward": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime ipv6-provider": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime tcd": libRSE.show_system_rsu_uptime,
        "show system rsu-uptime snmpd": libRSE.show_system_rsu_uptime,
        "show system app-status": libRSE.show_system_app_status,
        "show system ssh port": libRSE.show_system_ssh,
        "show system ssh timeout": libRSE.show_system_ssh,
        "show system ssh all": libRSE.show_system_ssh,
        "show system snmp-notification ipaddr": libRSE.show_system_snmp_notification,
        "show system snmp-notification port": libRSE.show_system_snmp_notification,
        "show system snmp-notification all": libRSE.show_system_snmp_notification,
        "show rsu-set all": libRSE.show_rsu_set,
        "show version": libRSE.show_version,
        "show serial-number": libRSE.show_serial,
        # "utils rsu-upgrade -n": utils_sys_upgrade,
        "utils reboot": libRSE.utils_reboot,
        "utils reboot status": libRSE.utils_reboot_status,
        "utils reset application-configuration": libRSE.utils_reset,
        "utils reset factory-defaults": libRSE.utils_reset,
        "utils rsu-upgrade -n": libRSE.utils_rsu_upgrade,
        "utils rsu-upgrade -c": libRSE.utils_rsu_upgrade,
        "utils standby": libRSE.utils_standby,
        "utils run": libRSE.utils_run,
        "utils list certificates": libRSE.utils_list,
        "utils list rsu-mib": libRSE.utils_list,
        "utils list timdb": libRSE.utils_list,
        "utils list tcd": libRSE.utils_list,
        "utils list system-log": libRSE.utils_list,
        "utils list interface-log ethernet rx": libRSE.utils_list,
        "utils list interface-log ethernet tx": libRSE.utils_list,
        "utils list interface-log radio1 rx": libRSE.utils_list,
        "utils list interface-log radio1 tx": libRSE.utils_list,
        "utils list interface-log radio2 rx": libRSE.utils_list,
        "utils list interface-log radio2 tx": libRSE.utils_list,
        "utils remove ?": libRSE.utils_list,
        "rsu ifconfig ath0": libRSE.rsu_ifconfig,
        "rsu ifconfig ath1": libRSE.rsu_ifconfig,
        "rsu ifconfig eth0": libRSE.rsu_ifconfig,
        "rsu ifconfig lo": libRSE.rsu_ifconfig,
        "cgps": libRSE.cgps,
        "coc app start": libRSE.coc_tcia_start,
        "ggaclient": libRSE.ggaclient,
        "file config": libRSE.file_config,
        "pr enable": libRSE.pr_enable,
        "privileged-mode enable": libRSE.pr_enable,
        "pr disable": libRSE.pr_enable,
        "privileged-mode disable": libRSE.pr_enable,
        "shell-drop": libRSE.shell_drop,
        "shell drop": libRSE.shell_drop,
        "shell-mode": libRSE.shell_mode,
        "shell mode": libRSE.shell_mode,
        "direct to shell mode": libRSE.direct_to_shell_mode,
        "remove files from path": libRSE.remove_files_from_path,
        "log error checker": libRSE.log_error_checker,
        "killall": libRSE.killall,
        "killall StoreRepeat": libRSE.killall,
        "killall ipv6_provider": libRSE.killall,
        "clear": libRSE.clear_fun,
        "rse_stats -t": libRSE.rse_stats,
        "rse_stats -d": libRSE.rse_stats,
        "rse_stats -s": libRSE.rse_stats,
        "rse_stats -i": libRSE.rse_stats,
        "rse_stats -u": libRSE.rse_stats,
        "rse_stats -D": libRSE.rse_stats,
        "rse_stats -R": libRSE.rse_stats,
        "rsu scp sys": libRSE.rsu_scp_sys,
        "show support log": libRSE.show_support_log,
        "show support-log": libRSE.show_support_log,
        "exit": libRSE.exit_fun,
        "sleep": libRSE.sleep_fun,
        "halt": libRSE.halt_run,
        "run": libRSE.halt_run,
        "ps": libRSE.sys_process,
        "tcpdump": libRSE.tcp_dump,
        "wsmp head decode": libRSE.wsmp_head,
        "ps | grep": libRSE.sys_process,
        "halt;run": libRSE.halt_run,
        "reboot": libRSE.reboot_func,
        "child close": libRSE.child_close,
        "obu file config": libRSE.obu_file_config,
        "obu v2x wsmptap bsm": libRSE.obu_v2x_wsmptap_bsm,
        "obu v2x_wsmptap_bsm": libRSE.obu_v2x_wsmptap_bsm,
        "obu v2x wsmptap tim": libRSE.obu_v2x_wsmptap_tim,
        "obu v2x_wsmptap_tim": libRSE.obu_v2x_wsmptap_tim,
        "obu v2vspidemo": libRSE.obu_v2vspidemo,
        "obu asd stats": libRSE.obu_asd_stats,
        "obu asd_stats -b": libRSE.obu_asd_stats,
        "obu asd_stats -i": libRSE.obu_asd_stats,
        "obu asd_stats -z": libRSE.obu_asd_stats,
        "obu asd_stats -s": libRSE.obu_asd_stats,
        "obu asd_stats -t": libRSE.obu_asd_stats,
        "obu asd_stats -r": libRSE.obu_asd_stats,
        "obu asd_stats -e": libRSE.obu_asd_stats,
        "obu asd_stats -S": libRSE.obu_asd_stats,
        "obu asd_stats -R": libRSE.obu_asd_stats,
        "obu asd_stats -a": libRSE.obu_asd_stats,
        "obu halt;run": libRSE.obu_halt_run,
        "obu halt": libRSE.obu_halt_run,
        "obu run": libRSE.obu_halt_run,
        "obu cat": libRSE.obu_cat,
        "obu cat /etc/banner": libRSE.obu_cat,
        "obu scp": libRSE.obu_scp,
        "obu scp sys": libRSE.obu_scp_sys,
        "obu cp": libRSE.obu_cp_func,
        "obu sysupgrade -n": libRSE.obu_run_command,
        "obu sysupgrade -c": libRSE.obu_run_command,
        "obu log error checker": libRSE.obu_log_error_checker,
        "obu clear fun": libRSE.obu_clear_fun,
        "obu wmectl -W": libRSE.obu_wmectl,
        "obu wmectl -r": libRSE.obu_wmectl,
        "obu wmectl -s": libRSE.obu_wmectl,
        "obu wsmp head decode": libRSE.wsmp_head,
        "obu tcpdump": libRSE.obu_tcpdump,
        "obu cgps": libRSE.obu_cgps,
        "obu ps": libRSE.obu_ps,
        "obu top": libRSE.obu_top,
        "obu df":  libRSE.obu_df,
        "obu mpstat": libRSE.obu_mpstat,
        "obu free": libRSE.obu_free,
        "obu reboot": libRSE.obu_reboot_func,
        "snmpset": libRSE.snmp_func,
        "snmpget": libRSE.snmp_func,
        "obu general command": libRSE.obu_general_command,
        "obu general command with pipe": libRSE.obu_general_command_with_pipe,
        "obu ifconfig ath0": libRSE.obu_ifconfig,
        "obu ifconfig ath1": libRSE.obu_ifconfig,
        "obu ifconfig can0": libRSE.obu_ifconfig,
        "obu ifconfig eth0": libRSE.obu_ifconfig,
        "obu ifconfig lo": libRSE.obu_ifconfig,
        "obu syslog config": libRSE.obu_syslog_config,
        "obu pcaplog config": libRSE.obu_syslog_config,
        "obu get newer syslog": libRSE.obu_get_newer_syslog_file,
        "rsu get newer syslog": libRSE.rsu_get_newer_syslog_file,
        "obu get older syslog": libRSE.obu_get_older_syslog_file,
        "obu get syslog filesize": libRSE.obu_get_last_syslog_size,
        "obu get newer pcaplog": libRSE.obu_get_newer_pcap_file,
        "obu get latency average": libRSE.obu_get_latency_average,
        "coc packet capture": coc_script.tshark_wrapper,
        "coc send command": coc_script.coc_script,
        "coc packet reader": coc_script.pcap_reader,
        "coc packet reader from psid": coc_script.pcap_reader_verify_psid,
        "coc get mac": coc_script.get_coc_mac,
        "coc obu get mac": coc_script.obu_get_coc_mac,
        "coc latest pcap": coc_script.latest_pcap,
        "coc obu latest pcap": coc_script.obu_latest_pcap,
        "coc pcap to csv": coc_script.pcap_to_csv,
        "coc pcap to csv rx case": coc_script.pcap_to_csv_rx_case,
        "coc std dev": coc_script.std_dev_cal,
        "general command": libRSE.general_command,
        "obu file read": libRSE.euobu_file_read,
        "obu eu_halt": libRSE.euobu_halt_run,
        "obu eu_run": libRSE.euobu_halt_run,
        "obu gntool get_locte": libRSE.euobu_gntool_getLocte,
        "obu eutcpdump": libRSE.euobu_tcpdump,
        "euobu process": libRSE.euobu_restart_process,
        "obu ca_config -k": libRSE.euobu_ca_config,
        "obu backup_defaultConf": libRSE.euobu_backup_defaultConf,
        "obu bsm log get and filter": bsm.filter_api,
        "obu bsm log get index": bsm.bsm_log_get_index,
        "obu bsm log get value": bsm.bsm_log_get_value,
        "obu euifconfig": libRSE.euobu_ifconfig,
        "obu select_stack EU": libRSE.euobu_select_stack,
        "obu select_stack US": libRSE.euobu_select_stack,
        "obu stack_in_use": libRSE.euobu_stack_in_use,
        "euobu ps": libRSE.euobu_sys_process,
        "euobu ps | grep": libRSE.euobu_sys_process,
        "obu eu_device_mode ASD": libRSE.euobu_eu_device_mode,
        "obu eu_device_mode RSU": libRSE.euobu_eu_device_mode,
        "obu eu_device_mode": libRSE.euobu_eu_device_mode,
        "obu EUV2Xd": libRSE.euobu_euv2xd,
        "obu EUV2Xd &": libRSE.euobu_euv2xd,
        "obu gn header decode": libRSE.etsi_head,
        "obu btp header decode": libRSE.etsi_head,
        "obu killall": libRSE.euobu_killall,
        #"obu ping":libRSE.obu_ping_statistics,
        #"rsu ping": libRSE.rsu_ping_statistics,
        "get timestamp from file": tc_specific.get_timestamp_from_file,
        "get timestamp from output": tc_specific.get_timestamp_from_output,
        "obu file config get": libRSE.obu_file_config_get,
        #"string operations":libRSE.string_operations,
        #"convert time to secs":tc_specific.convert_time_secs,
        "snmpget": libRSE.get_snmp_output,
        "snmpset": libRSE.set_snmp_output,
        "euobu XML file config": libRSE.euobu_XMl_file_config,
        "euobu XML file get": libRSE.euobu_XMl_file_config_get,
        "euobu dsrc_get_config ath0": libRSE.euobu_dsrc_get_config,
        "euobu dsrc_get_config ath1": libRSE.euobu_dsrc_get_config,
        "obu cat /proc/meminfo": libRSE.obu_asd_stats,
        # "obu ps | grep": libRSE.obu_sys_process,
        "rv simulation": libKPI.bsmd_rv_simulation,
        "cpu logger": libKPI.cpu_log,
        "cpu usage log": libKPI.rsu_cpu_usage_log,
        "obu cpu usage log": libKPI.obu_cpu_usage_log,
        "run pwr command": libKPI.run_pwr_switch_command,
        "get timestamp from file": libKPI.get_timestamp_from_file,
        "dict var value": libKPI.get_val_from_dict,
        "obu file copy": libKPI.pobu_file_copy,
        "packet count": libKPI.diff_fun,
        "rv copy": libKPI.rv_file_copy,
        "ifconfig": libKPI.if_stats,
        "str ext": libKPI.pstr_ext,
        "obu rmmod wlan0": libKPI.obu_run_command,
        "obu insmod wlan0": libKPI.obu_run_command,
        "obu ln -s": libKPI.obu_run_command,
        "obu rmmod wlan0": libKPI.obu_run_command,
        "obu insmod wlan0": libKPI.obu_run_command,
        "obu ln -s": libKPI.obu_run_command,
        "obu date": libRSE.obu_date,
        "obu hwclock": libRSE.obu_hwclock,
        "obu hwclock -c": libRSE.obu_hwclock_c,
        "convert time to secs": libRSE.convert_time_secs,
        "convert time to mins": libRSE.convert_time_mins,
        "convert secs to time": libRSE.convert_secs_into_time,
        "obu time change": libRSE.obu_time_change,
        "obu kmpstat": libKPI.mp_stat,
        "obu /etc/init.d/savari16093 start": libKPI.obu_run_command,
        "obu /etc/init.d/aerolink start": libKPI.obu_run_command,
        "obu /etc/init.d/bsmd start": libKPI.obu_run_command,
        "obu /etc/init.d/savari16093 stop": libKPI.obu_run_command,
        "obu /etc/init.d/aerolink stop": libKPI.obu_run_command,
        "obu /etc/init.d/bsmd stop": libKPI.obu_run_command,
        "obu BSMd -i /etc/config/ &": libKPI.obu_run_command,
        "file conv": libKPI.file_converter,
        "csv merge": libKPI.csv_merge,
        "r print": libKPI.rb_print,
        "clr file": libKPI.clr_file,
        "dict var": libKPI.get_from_dict,
        "utc loc": libKPI.utc_2_local,
        "mp extr": libKPI.mp_extr,
        "dmips conv": libKPI.dmips_conv,
        "csv plot": libKPI.csv_plotter,
        "obu ping": libRSE.obu_ping_statistics,
        "obu ping6": libRSE.obu_ping_statistics,
        "rsu ping": libRSE.rsu_ping_statistics,
        "rsu ping6": libRSE.rsu_ping_statistics,
        "show system ?": libRSE.show_system_all,
        "rsu utils ping ipv4": libRSE.rsu_utils_ping,
        "rsu utils ping ipv6": libRSE.rsu_utils_ping,
        "rsu file config get": libRSE.rsu_file_config_get,
        "rsu show traceroute ipv4": libRSE.rsu_show_traceroute,
        "rsu show traceroute ipv6": libRSE.rsu_show_traceroute,
        "file copy": libRSE.file_copy,
        "sudo copy": libRSE.sudo_copy,
        "obu graceshut": libRSE.obu_gracefull_shutdown_func,
        "euobu csv file comparison": cam.csv_file_comparison,
        "obu csv file comparison": bsm.csv_file_comparison,
        "euobu cam log get and filter": cam.filter_api,
        "euobu cam log get value": cam.cam_log_get_value,
        "euobu verify IG BIT": tc_specific.verify_IG_BIT,
        "euobu get acfinfo": libRSE.euobu_acfinfo,
        "obu get acfinfo": libRSE.obu_acfinfo,
        "obu etsifacility_stats -d": libRSE.euobu_etsifacility_stats,
        "obu etsifacility_stats -c": libRSE.euobu_etsifacility_stats,
        "euobu cam log field specific API": cam.cam_field_specific_api,
        "obu mem_info": libRSE.obu_meminfo,
        "WSMP QOS decode": libRSE.WSMP_QOS_decoding,
        "v2x_play": libRSE.eu_v2x_play,
        "euobu blackbox log field specific API": bblogs.bb_log_field_specific_api,
        "euobu blackbox log get and filter": bblogs.filter_api,
        "euobu blackbox log get value": bblogs.bb_log_get_value,
        "euobu CAM header decode": libRSE.euobu_CAM_decoding_PCAP,
        "euobu DENM header decode": libRSE.euobu_DENM_decoding_PCAP,
        "euobu csv log difference between TX and RX timestamp": cam.differance_between_TX_RX_time_stamp,
    }
    try:
        command = command.strip()
        return api_data_struct[command]
    except KeyError:
        print("KeyError occurred")
        print("Give the proper command")
        return None
